genai:
  llmProvider: openai
  llmModel: openai/gpt-oss-120b
  llmBaseUrl: https://logos.aet.cit.tum.de/v1
  sttProvider: local
  whisperModel: tiny
  ttsEnabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

auth:
  issuerUri: https://team-drops.stud.k8s.aet.cit.tum.de/realms/team-drops
  jwksUri: http://keycloak:8080/realms/team-drops/protocol/openid-connect/certs

keycloak:
  redirectUris:
    - https://team-drops.stud.k8s.aet.cit.tum.de/*
  webOrigins:
    - https://team-drops.stud.k8s.aet.cit.tum.de
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 300m
      memory: 1Gi

frontend:
  keycloakUrl: https://team-drops.stud.k8s.aet.cit.tum.de
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 128Mi

services:
  user:
    resources:
      requests:
        cpu: 50m
        memory: 160Mi
      limits:
        cpu: 150m
        memory: 384Mi
  learning:
    resources:
      requests:
        cpu: 50m
        memory: 160Mi
      limits:
        cpu: 150m
        memory: 384Mi
  progress:
    resources:
      requests:
        cpu: 50m
        memory: 160Mi
      limits:
        cpu: 150m
        memory: 384Mi

postgres:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

mongo:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingress:
  host: team-drops.stud.k8s.aet.cit.tum.de
  tls:
    enabled: true
    secretName: team-drops-tls
    clusterIssuer: letsencrypt-prod
